openapi: 3.0.1
info:
  title: monster-unicorn
  x-cortex-tag: monster-unicorn
  x-cortex-custom-metadata:
    alignment: chaotic-evil
    type: undead
    challenge_rating: 25
    legendary: true
    armor_class: 18
    hit_points: 184
    source: dnd-5e
  x-cortex-type: monster
  x-cortex-git:
    github:
      repository: xycia-cortex/monster-unicorn
      alias: github-token-test
